version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/flutter_lyform/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/lyform/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/lyform_validators/"
    schedule:
      interval: "daily"
