name: lynot-dart-flutter

packages:
  - packages/**

scripts:
  sync:
    run: melos exec -c 1 "lockpick sync ./"

  build:
    run: melos exec -c 1 "dart pub get && dart pub run build_runner build"

  build:all:
    run: melos exec -c 1 "dart pub get && dart pub run build_runner build --delete-conflicting-outputs"

  format:
    run: melos exec -c 1 "dart format ."

  test:format:
    run: melos exec -c 1 "dart format --set-exit-if-changed"

  test:analyze:
    run: melos exec -c 1 "dart analyze"

  test:only:
    run: melos exec -c 1 "dart test --no-pub --coverage"

  test:
    run: |
      melos run test:format
      melos run test:analyze
      melos run test:only

  coverage:install:
    run: |
      npm i -g lcov-result-merger
      flutter pub global activate remove_from_coverage

  coverage:
    run: |
      lcov-result-merger "packages/**/coverage/lcov.info" coverage/lcov.info
      remove_from_coverage -f coverage/lcov.info -r "\.freezed\.dart$","\.g\.dart$","\.config\.dart$","generated_plugin_registrant.dart$"

environment:
  sdk: ">=2.16.2 <3.0.0"

dev_dependencies:
  lint: ^1.8.2
