name: lyform_validators
description: Dart package to implement forms in an easy, fast and effective way using the bloc package
version: 0.14.0
homepage: https://github.com/lynotofficial/lynot-dart-flutter
repository: https://github.com/lynotofficial/lynot-dart-flutter/tree/master/packages/lyform_validators

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  lyform: ^0.14.0
  validators: ^3.0.0

dev_dependencies:
  lint: ^2.3.0
  mocktail: ^1.0.2
  test: ^1.25.0
