name: riverform
description: A dart form implementation using riverpod package.
version: 0.2.0

homepage: https://github.com/lynot/lynot-dart-flutter
repository: https://github.com/lynot/lynot-dart-flutter/tree/master/packages/riverform

environment:
   sdk: ">=3.0.0 <4.0.0"

dependencies:
  async: ^2.11.0
  equatable: ^2.0.5
  riverpod: ^2.4.9

dev_dependencies:
  lint: ^1.10.0
  test: ^1.25.0
