name: lyform
description: Dart package to implement forms in an easy, fast and effective way using the bloc package
version: 0.9.2
homepage: https://github.com/lynotofficial/lynot-dart-flutter
repository: https://github.com/lynotofficial/lynot-dart-flutter/tree/master/packages/lyform

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  bloc: ^8.0.3
  collection: ^1.16.0

dev_dependencies:
  lint: ^1.8.2
  mocktail: ^0.3.0
  test: ^1.21.1
