name: example
description: A Flutter example project for LyForm packages

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_lyform: ^0.5.3
  lyform_validators: ^0.5.2

dev_dependencies:
  lint: ^1.8.2

flutter:
  uses-material-design: true
