name: example
description: A Flutter example project for LyForm packages

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_lyform: ^0.13.0
  lyform_validators: ^0.12.0
dev_dependencies:
  lint: ^1.10.0

flutter:
  uses-material-design: true
