name: example
description: A Flutter example project for LyForm packages

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_lyform: ^0.13.0+1
  lyform_validators: ^0.13.0+1
dev_dependencies:
  lint: ^1.10.0

flutter:
  uses-material-design: true
