name: flutter_lyform
description: Flutter package to implement forms in an easy, fast and effective way using the lyform and flutter_bloc packages.
version: 0.13.0+1
homepage: https://github.com/lynotofficial/lynot-dart-flutter
repository: https://github.com/lynotofficial/lynot-dart-flutter/tree/master/packages/flutter_lyform

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  # lyform: ^0.13.0+1
  lyform: 
    path: ../lyform
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.2.0
  mocktail: ^1.0.1
