name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Install Melos
        run: flutter pub global activate melos

      - name: Run Melos Bootstrap
        run: melos bs

      - name: Run Tests
        run: melos run test

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
