name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3

      - name: Install lcov-result-merger
        run: npm i -g lcov-result-merger

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Install 'Remove from coverage'
        run: flutter pub global activate remove_from_coverage

      - name: Install Melos
        run: flutter pub global activate melos

      - name: Run Melos Bootstrap
        run: melos bs

      - name: Run Tests
        run: melos run test

      - name: Run Coverage
        run: melos run coverage

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: coverage/lcov.info
